spring:
  datasource:
    name: demo
    url: localhost
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-wait: 30000
        max-idle: 20
        max-active: 100
        min-idle: 0
    connect-timeout: 3000

server:
  port: 8888

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.bean